// <auto-generated />
using System;
using MauiTrainApp.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MauiTrainApp.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MauiTrainAppDbContext))]
    [Migration("20260912110014_AddWorkoutStartedAt")]
    partial class AddWorkoutStartedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.ExerciseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.ExerciseSetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExerciseRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainingPlanRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingSets")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkoutRecordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseRecordId");

                    b.HasIndex("TrainingPlanRecordId");

                    b.HasIndex("WorkoutRecordId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.TrainingPlanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.WorkoutRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainingPlanRecordId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkoutDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanRecordId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.ExerciseSetRecord", b =>
                {
                    b.HasOne("MauiTrainApp.Infrastructure.Records.ExerciseRecord", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MauiTrainApp.Infrastructure.Records.TrainingPlanRecord", null)
                        .WithMany("ExerciseSets")
                        .HasForeignKey("TrainingPlanRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MauiTrainApp.Infrastructure.Records.WorkoutRecord", null)
                        .WithMany("ExerciseSets")
                        .HasForeignKey("WorkoutRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.WorkoutRecord", b =>
                {
                    b.HasOne("MauiTrainApp.Infrastructure.Records.TrainingPlanRecord", "TrainingPlan")
                        .WithMany()
                        .HasForeignKey("TrainingPlanRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.TrainingPlanRecord", b =>
                {
                    b.Navigation("ExerciseSets");
                });

            modelBuilder.Entity("MauiTrainApp.Infrastructure.Records.WorkoutRecord", b =>
                {
                    b.Navigation("ExerciseSets");
                });
#pragma warning restore 612, 618
        }
    }
}
